// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7-tvdx_fk8pr6vBM36PJFG17Y1dPkzSM',
    appId: '1:952344786805:web:54a2b74fb25cc6ca86853c',
    messagingSenderId: '952344786805',
    projectId: 'lavinis',
    authDomain: 'lavinis.firebaseapp.com',
    storageBucket: 'lavinis.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbrE3ZYfuT0af-4xXWoNk5A4TaEfvtLp0',
    appId: '1:952344786805:android:2d28a1e533ce411186853c',
    messagingSenderId: '952344786805',
    projectId: 'lavinis',
    storageBucket: 'lavinis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARF0Pa7-4Wvj3UV5gQxYl68ODyPqJPhy8',
    appId: '1:952344786805:ios:1ab679c9b0aca3c286853c',
    messagingSenderId: '952344786805',
    projectId: 'lavinis',
    storageBucket: 'lavinis.appspot.com',
    iosBundleId: 'com.example.lavinis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARF0Pa7-4Wvj3UV5gQxYl68ODyPqJPhy8',
    appId: '1:952344786805:ios:1ab679c9b0aca3c286853c',
    messagingSenderId: '952344786805',
    projectId: 'lavinis',
    storageBucket: 'lavinis.appspot.com',
    iosBundleId: 'com.example.lavinis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7-tvdx_fk8pr6vBM36PJFG17Y1dPkzSM',
    appId: '1:952344786805:web:0286c6d74467dcc686853c',
    messagingSenderId: '952344786805',
    projectId: 'lavinis',
    authDomain: 'lavinis.firebaseapp.com',
    storageBucket: 'lavinis.appspot.com',
  );
}
